### PR TITLE
Add demojify

### PR DESCRIPTION
**Pull request by immjs**
Can be useful to detect the actual length of text before sending

### CODE REVIEW

**Comment by ArkinSolomon** [comment]
Can you ensure that your code passes all the tests, as well as write your own tests.

**Comment by immjs** [comment]
Ah yes, sorry 😅

Ill do this right now

**Comment by ArkinSolomon** [comment]
Line 67 fails when it encounters a non existent shortcode. A shortcode like :cheeseburger: should be skipped over. You can try wrapping it in a try catch similar to its current implementation.

You also still need to write tests for the `demojify()` function. Or at least provide me examples of what it's supposed to output and I can try to write them.

**Comment by immjs** [comment]
Oh yes, i guess I couldn't find time for this PR
It should be done within tomorrow
Sorry 😅 school is tough

**Comment by immjs** [comment]
@ArkinSolomon Hey, I did tests and fixed emojify, could you run the workflow?

**Comment by ArkinSolomon** [comment]
Code looks good, tests passed, could you add just a little bit to the readme. I can merge and publish after that. Feel free to add yourself to the contributors as well.

**Comment by immjs** [comment]
All should be well :)

Again, sorry for all the delay, took my mind off coding for a bit

**Comment by immjs** [comment]
Hey @ArkinSolomon , any chance you can get it merged now?

**Comment by ArkinSolomon** [comment]
Merged and published! Thanks for your contribution!

**Pull request merged**
